FROM node:22-alpine AS base

RUN apk add --no-cache libc6-compat \
    && corepack enable \
    && corepack prepare yarn@4.10.3 --activate
WORKDIR /app

# STAGE 1: prune stage
FROM base AS prune

COPY turbo.json ./
COPY package.json yarn.lock ./
COPY .yarn/ .yarn/
COPY .yarnrc.yml ./

COPY admin ./admin
COPY web ./web
COPY packages ./packages

RUN yarn dlx turbo@^2 prune --scope=web --docker

# STAGE 2: install deps
FROM base AS install

COPY --from=prune /app/out/json/ ./
COPY --from=prune /app/out/yarn.lock ./yarn.lock

COPY --from=prune /app/.yarn/ ./.yarn/
COPY --from=prune /app/.yarnrc.yml ./.yarnrc.yml

RUN yarn install --immutable

# STAGE 3: build the app
FROM base AS build

COPY --from=prune /app/out/full/ ./
COPY --from=install /app/.yarn/ ./.yarn/
COPY --from=install /app/.yarnrc.yml ./
COPY --from=install /app/yarn.lock ./yarn.lock
COPY --from=install /app/node_modules ./node_modules

ARG NEXT_PUBLIC_API_BASE_URL=""
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

ARG NEXT_PUBLIC_ADMIN_BASE_URL=""
ENV NEXT_PUBLIC_ADMIN_BASE_URL=$NEXT_PUBLIC_ADMIN_BASE_URL

ARG NEXT_PUBLIC_ADMIN_BASE_PATH="/god-mode"
ENV NEXT_PUBLIC_ADMIN_BASE_PATH=$NEXT_PUBLIC_ADMIN_BASE_PATH

ARG NEXT_PUBLIC_WEB_BASE_URL=""
ENV NEXT_PUBLIC_WEB_BASE_URL=$NEXT_PUBLIC_WEB_BASE_URL

RUN yarn dlx turbo@^2 run build --filter=./web

# STAGE 4: runtime
FROM node:22-alpine AS runner
ENV NODE_ENV=production
ENV PORT=3000
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs
WORKDIR /app

COPY --from=build /app/web/.next/standalone ./

COPY --from=build /app/web/.next/static ./web/.next/static
COPY --from=build /app/web/public ./web/public

ARG NEXT_PUBLIC_API_BASE_URL=""
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

ARG NEXT_PUBLIC_ADMIN_BASE_URL=""
ENV NEXT_PUBLIC_ADMIN_BASE_URL=$NEXT_PUBLIC_ADMIN_BASE_URL

ARG NEXT_PUBLIC_ADMIN_BASE_PATH="/god-mode"
ENV NEXT_PUBLIC_ADMIN_BASE_PATH=$NEXT_PUBLIC_ADMIN_BASE_PATH

ARG NEXT_PUBLIC_WEB_BASE_URL=""
ENV NEXT_PUBLIC_WEB_BASE_URL=$NEXT_PUBLIC_WEB_BASE_URL

USER nextjs
EXPOSE 3000

CMD ["node", "web/server.js"]
